import { Component, OnInit } from '@angular/core';
import { Operacao } from '../shared/operacao';
import {Message, MessageService} from 'primeng/api';
import { Register } from './servico/register';
import { RegisterDados } from './servico/registerdados';
import { RegisterService } from './servico/register.service';

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.scss']
})
export class RegisterComponent implements OnInit {

  register:Register = new Register();
  registerDados:RegisterDados = new RegisterDados();

  operacao:any = '';

  msgs2: Message[] = []

  listaCidade:any [] = [];

  listaRegiao:any [] = [];

  constructor(
    private registerService: RegisterService,
    private messageService: MessageService, 
    ) {}

  ngOnInit() {
    this.operacao = Operacao.REGISTER;
    this.register = new Register();
    this.registerDados = new RegisterDados();

    this.listaCidade = [
      
      {name: 'Adamantina', code: 'SP'},
      {name: 'Adolfo', code: 'SP'},
      {name: 'Aguaí', code: 'SP'},
      {name: 'Águas da Prata', code: 'SP'},
      {name: 'Águas de Lindóia', code: 'SP'},
      {name: 'Águas de Santa Bárbara', code: 'SP'},
      {name: 'Águas de São Pedro', code: 'SP'},
      {name: 'Agudos', code: 'SP'},
      {name: 'Alambari', code: 'SP'},
      {name: 'Alfredo Marcondes', code: 'SP'},
      {name: 'Altair', code: 'SP'},
      {name: 'Altinópolis', code: 'SP'},
      {name: 'Alto Alegre', code: 'SP'},
      {name: 'Alumínio', code: 'SP'},
      {name: 'Álvares Florence', code: 'SP'},
      {name: 'Álvares Machado', code: 'SP'},
      {name: 'Álvaro de Carvalho', code: 'SP'},
      {name: 'Alvinlândia', code: 'SP'},
      {name: 'Americana', code: 'SP'},
      {name: 'Américo Brasiliense', code: 'SP'},
      {name: 'Américo de Campos', code: 'SP'},
      {name: 'Amparo', code: 'SP'},
      {name: 'Analândia', code: 'SP'},
      {name: 'Andradina', code: 'SP'},
      {name: 'Angatuba', code: 'SP'},
      {name: 'Anhembi', code: 'SP'},
      {name: 'Anhumas', code: 'SP'},
      {name: 'Aparecida', code: 'SP'},
      {name: 'Aparecida do Oeste', code: 'SP'},
      {name: 'Apiaí', code: 'SP'},
      {name: 'Araçariguama', code: 'SP'},
      {name: 'Araçatuba', code: 'SP'},
      {name: 'Araçoiaba da Serra', code: 'SP'},
      {name: 'Aramina', code: 'SP'},
      {name: 'Arandu', code: 'SP'},
      {name: 'Arapeí', code: 'SP'},
      {name: 'Araraquara', code: 'SP'},
      {name: 'Araras', code: 'SP'},
      {name: 'Arco-Íris', code: 'SP'},
      {name: 'Arealva', code: 'SP'},
      {name: 'Areias', code: 'SP'},
      {name: 'Areiópolis', code: 'SP'},
      {name: 'Ariranha', code: 'SP'},
      {name: 'Artur Nogueira', code: 'SP'},
      {name: 'Arujá', code: 'SP'},
      {name: 'Aspásia', code: 'SP'},
      {name: 'Assis', code: 'SP'},
      {name: 'Atibaia', code: 'SP'},
      {name: 'Auriflama', code: 'SP'},
      {name: 'Avaí', code: 'SP'},
      {name: 'Avanhandava', code: 'SP'},
      {name: 'Avaré', code: 'SP'},
      {name: 'Bady Bassitt', code: 'SP'},
      {name: 'Balbinos', code: 'SP'},
      {name: 'Bálsamo', code: 'SP'},
      {name: 'Bananal', code: 'SP'},
      {name: 'Barão de Antonina', code: 'SP'},
      {name: 'Barbosa', code: 'SP'},
      {name: 'Bariri', code: 'SP'},
      {name: 'Barra Bonita', code: 'SP'},
      {name: 'Barra do Chapéu', code: 'SP'},
      {name: 'Barra do Turvo', code: 'SP'},
      {name: 'Barretos', code: 'SP'},
      {name: 'Barrinha', code: 'SP'},
      {name: 'Barueri', code: 'SP'},
      {name: 'Bastos', code: 'SP'},
      {name: 'Batatais', code: 'SP'},
      {name: 'Bauru', code: 'SP'},
      {name: 'Bebedouro', code: 'SP'},
      {name: 'Bento de Abreu', code: 'SP'},
      {name: 'Bernardino de Campos', code: 'SP'},
      {name: 'Bertioga', code: 'SP'},
      {name: 'Bilac', code: 'SP'},
      {name: 'Birigui', code: 'SP'},
      {name: 'Biritiba-Mirim', code: 'SP'},
      {name: 'Boa Esperança do Sul', code: 'SP'},
      {name: 'Bocaina', code: 'SP'},
      {name: 'Bofete', code: 'SP'},
      {name: 'Boituva', code: 'SP'},
      {name: 'Bom Jesus dos Perdões', code: 'SP'},
      {name: 'Bom Sucesso de Itararé', code: 'SP'},
      {name: 'Borá', code: 'SP'},
      {name: 'Boracéia', code: 'SP'},
      {name: 'Borborema', code: 'SP'},
      {name: 'Borebi', code: 'SP'},
      {name: 'Botucatu', code: 'SP'},
      {name: 'Bragança Paulista', code: 'SP'},
      {name: 'Braúna', code: 'SP'},
      {name: 'Brejo Alegre', code: 'SP'},
      {name: 'Brodowski', code: 'SP'},
      {name: 'Brotas', code: 'SP'},
      {name: 'Buri', code: 'SP'},
      {name: 'Buritama', code: 'SP'},
      {name: 'Buritizal', code: 'SP'},
      {name: 'Cabrália Paulista', code: 'SP'},
      {name: 'Cabreúva', code: 'SP'},
      {name: 'Caçapava', code: 'SP'},
      {name: 'Cachoeira Paulista', code: 'SP'},
      {name: 'Caconde', code: 'SP'},
      {name: 'Cafelândia', code: 'SP'},
      {name: 'Caiabu', code: 'SP'},
      {name: 'Caieiras', code: 'SP'},
      {name: 'Caiuá', code: 'SP'},
      {name: 'Cajamar', code: 'SP'},
      {name: 'Cajati', code: 'SP'},
      {name: 'Cajobi', code: 'SP'},
      {name: 'Cajuru', code: 'SP'},
      {name: 'Campina do Monte Alegre', code: 'SP'},
      {name: 'Campinas', code: 'SP'},
      {name: 'Campo Limpo Paulista', code: 'SP'},
      {name: 'Campos do Jordão', code: 'SP'},
      {name: 'Campos Novos Paulista', code: 'SP'},
      {name: 'Cananéia', code: 'SP'},
      {name: 'Canas', code: 'SP'},
      {name: 'Cândido Mota', code: 'SP'},
      {name: 'Cândido Rodrigues', code: 'SP'},
      {name: 'Canitar', code: 'SP'},
      {name: 'Capão Bonito', code: 'SP'},
      {name: 'Capela do Alto', code: 'SP'},
      {name: 'Capivari', code: 'SP'},
      {name: 'Caraguatatuba', code: 'SP'},
      {name: 'Carapicuíba', code: 'SP'},
      {name: 'Cardoso', code: 'SP'},
      {name: 'Casa Branca', code: 'SP'},
      {name: 'Cássia dos Coqueiros', code: 'SP'},
      {name: 'Castilho', code: 'SP'},
      {name: 'Catanduva', code: 'SP'},
      {name: 'Catiguá', code: 'SP'},
      {name: 'Cedral', code: 'SP'},
      {name: 'Cerqueira César', code: 'SP'},
      {name: 'Cerquilho', code: 'SP'},
      {name: 'Cesário Lange', code: 'SP'},
      {name: 'Charqueada', code: 'SP'},
      {name: 'Chavantes', code: 'SP'},
      {name: 'Clementina', code: 'SP'},
      {name: 'Colina', code: 'SP'},
      {name: 'Colômbia', code: 'SP'},
      {name: 'Conchal', code: 'SP'},
      {name: 'Conchas', code: 'SP'},
      {name: 'Cordeirópolis', code: 'SP'},
      {name: 'Coroados', code: 'SP'},
      {name: 'Coronel Macedo', code: 'SP'},
      {name: 'Corumbataí', code: 'SP'},
      {name: 'Cosmópolis', code: 'SP'},
      {name: 'Cosmorama', code: 'SP'},
      {name: 'Cotia', code: 'SP'},
      {name: 'Cravinhos', code: 'SP'},
      {name: 'Cristais Paulista', code: 'SP'},
      {name: 'Cruzália', code: 'SP'},
      {name: 'Cruzeiro', code: 'SP'},
      {name: 'Cubatão', code: 'SP'},
      {name: 'Cunha', code: 'SP'},
      {name: 'Descalvado', code: 'SP'},
      {name: 'Diadema', code: 'SP'},
      {name: 'Dirce Reis', code: 'SP'},
      {name: 'Divinolândia', code: 'SP'},
      {name: 'Dobrada', code: 'SP'},
      {name: 'Dois Córregos', code: 'SP'},
      {name: 'Dolcinópolis', code: 'SP'},
      {name: 'Dourado', code: 'SP'},
      {name: 'Dracena', code: 'SP'},
      {name: 'Duartina', code: 'SP'},
      {name: 'Dumont', code: 'SP'},
      {name: 'Echaporã', code: 'SP'},
      {name: 'Eldorado', code: 'SP'},
      {name: 'Elias Fausto', code: 'SP'},
      {name: 'Elisiário', code: 'SP'},
      {name: 'Embaúba', code: 'SP'},
      {name: 'Embu', code: 'SP'},
      {name: 'Embu-Guaçu', code: 'SP'},
      {name: 'Emilianópolis', code: 'SP'},
      {name: 'Engenheiro Coelho', code: 'SP'},
      {name: 'Espírito Santo do Pinhal', code: 'SP'},
      {name: 'Espírito Santo do Turvo', code: 'SP'},
      {name: 'Estiva Gerbi', code: 'SP'},
      {name: 'Estrela do Oeste', code: 'SP'},
      {name: 'Estrela do Norte', code: 'SP'},
      {name: 'Euclides da Cunha Paulista', code: 'SP'},
      {name: 'Fartura', code: 'SP'},
      {name: 'Fernando Prestes', code: 'SP'},
      {name: 'Fernandópolis', code: 'SP'},
      {name: 'Fernão', code: 'SP'},
      {name: 'Ferraz de Vasconcelos', code: 'SP'},
      {name: 'Flora Rica', code: 'SP'},
      {name: 'Floreal', code: 'SP'},
      {name: 'Florínia', code: 'SP'},
      {name: 'Flórida Paulista', code: 'SP'},
      {name: 'Franca', code: 'SP'},
      {name: 'Francisco Morato', code: 'SP'},
      {name: 'Franco da Rocha', code: 'SP'},
      {name: 'Gabriel Monteiro', code: 'SP'},
      {name: 'Gália', code: 'SP'},
      {name: 'Garça', code: 'SP'},
      {name: 'Gastão Vidigal', code: 'SP'},
      {name: 'Gavião Peixoto', code: 'SP'},
      {name: 'General Salgado', code: 'SP'},
      {name: 'Getulina', code: 'SP'},
      {name: 'Glicério', code: 'SP'},
      {name: 'Guaiçara', code: 'SP'},
      {name: 'Guaimbê', code: 'SP'},
      {name: 'Guaíra', code: 'SP'},
      {name: 'Guapiaçu', code: 'SP'},
      {name: 'Guapiara', code: 'SP'},
      {name: 'Guará', code: 'SP'},
      {name: 'Guaraçaí', code: 'SP'},
      {name: 'Guaraci', code: 'SP'},
      {name: 'Guarani do Oeste', code: 'SP'},
      {name: 'Guarantã', code: 'SP'},
      {name: 'Guararapes', code: 'SP'},
      {name: 'Guararema', code: 'SP'},
      {name: 'Guaratinguetá', code: 'SP'},
      {name: 'Guareí', code: 'SP'},
      {name: 'Guariba', code: 'SP'},
      {name: 'Guarujá', code: 'SP'},
      {name: 'Guarulhos', code: 'SP'},
      {name: 'Guatapará', code: 'SP'},
      {name: 'Guzolândia', code: 'SP'},
      {name: 'Herculândia', code: 'SP'},
      {name: 'Holambra', code: 'SP'},
      {name: 'Hortolândia', code: 'SP'},
      {name: 'Iacanga', code: 'SP'},
      {name: 'Iacri', code: 'SP'},
      {name: 'Iaras', code: 'SP'},
      {name: 'Ibaté', code: 'SP'},
      {name: 'Ibirá', code: 'SP'},
      {name: 'Ibirarema', code: 'SP'},
      {name: 'Ibitinga', code: 'SP'},
      {name: 'Ibiúna', code: 'SP'},
      {name: 'Icém', code: 'SP'},
      {name: 'Iepê', code: 'SP'},
      {name: 'Igaraçu do Tietê', code: 'SP'},
      {name: 'Igarapava', code: 'SP'},
      {name: 'Igaratá', code: 'SP'},
      {name: 'Iguape', code: 'SP'},
      {name: 'Ilha Comprida', code: 'SP'},
      {name: 'Ilha Solteira', code: 'SP'},
      {name: 'Ilhabela', code: 'SP'},
      {name: 'Indaiatuba', code: 'SP'},
      {name: 'Indiana', code: 'SP'},
      {name: 'Indiaporã', code: 'SP'},
      {name: 'Inúbia Paulista', code: 'SP'},
      {name: 'Ipauçu', code: 'SP'},
      {name: 'Iperó', code: 'SP'},
      {name: 'Ipeúna', code: 'SP'},
      {name: 'Ipiguá', code: 'SP'},
      {name: 'Iporanga', code: 'SP'},
      {name: 'Ipuã', code: 'SP'},
      {name: 'Iracemápolis', code: 'SP'},
      {name: 'Irapuã', code: 'SP'},
      {name: 'Irapuru', code: 'SP'},
      {name: 'Itaberá', code: 'SP'},
      {name: 'Itaí', code: 'SP'},
      {name: 'Itajobi', code: 'SP'},
      {name: 'Itaju', code: 'SP'},
      {name: 'Itanhaém', code: 'SP'},
      {name: 'Itaóca', code: 'SP'},
      {name: 'Itapecerica da Serra', code: 'SP'},
      {name: 'Itapetininga', code: 'SP'},
      {name: 'Itapeva', code: 'SP'},
      {name: 'Itapevi', code: 'SP'},
      {name: 'Itapira', code: 'SP'},
      {name: 'Itapirapuã Paulista', code: 'SP'},
      {name: 'Itápolis', code: 'SP'},
      {name: 'Itaporanga', code: 'SP'},
      {name: 'Itapuí', code: 'SP'},
      {name: 'Itapura', code: 'SP'},
      {name: 'Itaquaquecetuba', code: 'SP'},
      {name: 'Itararé', code: 'SP'},
      {name: 'Itariri', code: 'SP'},
      {name: 'Itatiba', code: 'SP'},
      {name: 'Itatinga', code: 'SP'},
      {name: 'Itirapina', code: 'SP'},
      {name: 'Itirapuã', code: 'SP'},
      {name: 'Itobi', code: 'SP'},
      {name: 'Itu', code: 'SP'},
      {name: 'Itupeva', code: 'SP'},
      {name: 'Ituverava', code: 'SP'},
      {name: 'Jaborandi', code: 'SP'},
      {name: 'Jaboticabal', code: 'SP'},
      {name: 'Jacareí', code: 'SP'},
      {name: 'Jaci', code: 'SP'},
      {name: 'Jacupiranga', code: 'SP'},
      {name: 'Jaguariúna', code: 'SP'},
      {name: 'Jales', code: 'SP'},
      {name: 'Jambeiro', code: 'SP'},
      {name: 'Jandira', code: 'SP'},
      {name: 'Jardinópolis', code: 'SP'},
      {name: 'Jarinu', code: 'SP'},
      {name: 'Jaú', code: 'SP'},
      {name: 'Jeriquara', code: 'SP'},
      {name: 'Joanópolis', code: 'SP'},
      {name: 'João Ramalho', code: 'SP'},
      {name: 'José Bonifácio', code: 'SP'},
      {name: 'Júlio Mesquita', code: 'SP'},
      {name: 'Jumirim', code: 'SP'},
      {name: 'Jundiaí', code: 'SP'},
      {name: 'Junqueirópolis', code: 'SP'},
      {name: 'Juquiá', code: 'SP'},
      {name: 'Juquitiba', code: 'SP'},
      {name: 'Lagoinha', code: 'SP'},
      {name: 'Laranjal Paulista', code: 'SP'},
      {name: 'Lavínia', code: 'SP'},
      {name: 'Lavrinhas', code: 'SP'},
      {name: 'Leme', code: 'SP'},
      {name: 'Lençóis Paulista', code: 'SP'},
      {name: 'Limeira', code: 'SP'},
      {name: 'Lindóia', code: 'SP'},
      {name: 'Lins', code: 'SP'},
      {name: 'Lorena', code: 'SP'},
      {name: 'Lourdes', code: 'SP'},
      {name: 'Louveira', code: 'SP'},
      {name: 'Lucélia', code: 'SP'},
      {name: 'Lucianópolis', code: 'SP'},
      {name: 'Luís Antônio', code: 'SP'},
      {name: 'Luiziânia', code: 'SP'},
      {name: 'Lupércio', code: 'SP'},
      {name: 'Lutécia', code: 'SP'},
      {name: 'Macatuba', code: 'SP'},
      {name: 'Macaubal', code: 'SP'},
      {name: 'Macedônia', code: 'SP'},
      {name: 'Magda', code: 'SP'},
      {name: 'Mairinque', code: 'SP'},
      {name: 'Mairiporã', code: 'SP'},
      {name: 'Manduri', code: 'SP'},
      {name: 'Marabá Paulista', code: 'SP'},
      {name: 'Maracaí', code: 'SP'},
      {name: 'Marapoama', code: 'SP'},
      {name: 'Mariápolis', code: 'SP'},
      {name: 'Marília', code: 'SP'},
      {name: 'Marinópolis', code: 'SP'},
      {name: 'Martinópolis', code: 'SP'},
      {name: 'Matão', code: 'SP'},
      {name: 'Mauá', code: 'SP'},
      {name: 'Mendonça', code: 'SP'},
      {name: 'Meridiano', code: 'SP'},
      {name: 'Mesópolis', code: 'SP'},
      {name: 'Miguelópolis', code: 'SP'},
      {name: 'Mineiros do Tietê', code: 'SP'},
      {name: 'Mira Estrela', code: 'SP'},
      {name: 'Miracatu', code: 'SP'},
      {name: 'Mirandópolis', code: 'SP'},
      {name: 'Mirante do Paranapanema', code: 'SP'},
      {name: 'Mirassol', code: 'SP'},
      {name: 'Mirassolândia', code: 'SP'},
      {name: 'Mococa', code: 'SP'},
      {name: 'Mogi das Cruzes', code: 'SP'},
      {name: 'Mogi-Guaçu', code: 'SP'},
      {name: 'Mogi-Mirim', code: 'SP'},
      {name: 'Mombuca', code: 'SP'},
      {name: 'Monções', code: 'SP'},
      {name: 'Mongaguá', code: 'SP'},
      {name: 'Monte Alegre do Sul', code: 'SP'},
      {name: 'Monte Alto', code: 'SP'},
      {name: 'Monte Aprazível', code: 'SP'},
      {name: 'Monte Azul Paulista', code: 'SP'},
      {name: 'Monte Castelo', code: 'SP'},
      {name: 'Monte Mor', code: 'SP'},
      {name: 'Monteiro Lobato', code: 'SP'},
      {name: 'Morro Agudo', code: 'SP'},
      {name: 'Morungaba', code: 'SP'},
      {name: 'Motuca', code: 'SP'},
      {name: 'Murutinga do Sul', code: 'SP'},
      {name: 'Nantes', code: 'SP'},
      {name: 'Narandiba', code: 'SP'},
      {name: 'Natividade da Serra', code: 'SP'},
      {name: 'Nazaré Paulista', code: 'SP'},
      {name: 'Neves Paulista', code: 'SP'},
      {name: 'Nhandeara', code: 'SP'},
      {name: 'Nipoã', code: 'SP'},
      {name: 'Nova Aliança', code: 'SP'},
      {name: 'Nova Campina', code: 'SP'},
      {name: 'Nova Canaã Paulista', code: 'SP'},
      {name: 'Nova Castilho', code: 'SP'},
      {name: 'Nova Europa', code: 'SP'},
      {name: 'Nova Granada', code: 'SP'},
      {name: 'Nova Guataporanga', code: 'SP'},
      {name: 'Nova Independência', code: 'SP'},
      {name: 'Nova Luzitânia', code: 'SP'},
      {name: 'Nova Odessa', code: 'SP'},
      {name: 'Novais', code: 'SP'},
      {name: 'Novo Horizonte', code: 'SP'},
      {name: 'Nuporanga', code: 'SP'},
      {name: 'Ocauçu', code: 'SP'},
      {name: 'Óleo', code: 'SP'},
      {name: 'Olímpia', code: 'SP'},
      {name: 'Onda Verde', code: 'SP'},
      {name: 'Oriente', code: 'SP'},
      {name: 'Orindiúva', code: 'SP'},
      {name: 'Orlândia', code: 'SP'},
      {name: 'Osasco', code: 'SP'},
      {name: 'Oscar Bressane', code: 'SP'},
      {name: 'Osvaldo Cruz', code: 'SP'},
      {name: 'Ourinhos', code: 'SP'},
      {name: 'Ouro Verde', code: 'SP'},
      {name: 'Ouroeste', code: 'SP'},
      {name: 'Pacaembu', code: 'SP'},
      {name: 'Palestina', code: 'SP'},
      {name: 'Palmares Paulista', code: 'SP'},
      {name: 'Palmeira do Oeste', code: 'SP'},
      {name: 'Palmital', code: 'SP'},
      {name: 'Panorama', code: 'SP'},
      {name: 'Paraguaçu Paulista', code: 'SP'},
      {name: 'Paraibuna', code: 'SP'},
      {name: 'Paraíso', code: 'SP'},
      {name: 'Paranapanema', code: 'SP'},
      {name: 'Paranapuã', code: 'SP'},
      {name: 'Parapuã', code: 'SP'},
      {name: 'Pardinho', code: 'SP'},
      {name: 'Pariquera-Açu', code: 'SP'},
      {name: 'Parisi', code: 'SP'},
      {name: 'Patrocínio Paulista', code: 'SP'},
      {name: 'Paulicéia', code: 'SP'},
      {name: 'Paulínia', code: 'SP'},
      {name: 'Paulistânia', code: 'SP'},
      {name: 'Paulo de Faria', code: 'SP'},
      {name: 'Pederneiras', code: 'SP'},
      {name: 'Pedra Bela', code: 'SP'},
      {name: 'Pedranópolis', code: 'SP'},
      {name: 'Pedregulho', code: 'SP'},
      {name: 'Pedreira', code: 'SP'},
      {name: 'Pedrinhas Paulista', code: 'SP'},
      {name: 'Pedro de Toledo', code: 'SP'},
      {name: 'Penápolis', code: 'SP'},
      {name: 'Pereira Barreto', code: 'SP'},
      {name: 'Pereiras', code: 'SP'},
      {name: 'Peruíbe', code: 'SP'},
      {name: 'Piacatu', code: 'SP'},
      {name: 'Piedade', code: 'SP'},
      {name: 'Pilar do Sul', code: 'SP'},
      {name: 'Pindamonhangaba', code: 'SP'},
      {name: 'Pindorama', code: 'SP'},
      {name: 'Pinhalzinho', code: 'SP'},
      {name: 'Piquerobi', code: 'SP'},
      {name: 'Piquete', code: 'SP'},
      {name: 'Piracaia', code: 'SP'},
      {name: 'Piracicaba', code: 'SP'},
      {name: 'Piraju', code: 'SP'},
      {name: 'Pirajuí', code: 'SP'},
      {name: 'Pirangi', code: 'SP'},
      {name: 'Pirapora do Bom Jesus', code: 'SP'},
      {name: 'Pirapozinho', code: 'SP'},
      {name: 'Pirassununga', code: 'SP'},
      {name: 'Piratininga', code: 'SP'},
      {name: 'Pitangueiras', code: 'SP'},
      {name: 'Planalto', code: 'SP'},
      {name: 'Platina', code: 'SP'},
      {name: 'Poá', code: 'SP'},
      {name: 'Poloni', code: 'SP'},
      {name: 'Pompéia', code: 'SP'},
      {name: 'Pongaí', code: 'SP'},
      {name: 'Pontal', code: 'SP'},
      {name: 'Pontalinda', code: 'SP'},
      {name: 'Pontes Gestal', code: 'SP'},
      {name: 'Populina', code: 'SP'},
      {name: 'Porangaba', code: 'SP'},
      {name: 'Porto Feliz', code: 'SP'},
      {name: 'Porto Ferreira', code: 'SP'},
      {name: 'Potim', code: 'SP'},
      {name: 'Potirendaba', code: 'SP'},
      {name: 'Pracinha', code: 'SP'},
      {name: 'Pradópolis', code: 'SP'},
      {name: 'Praia Grande', code: 'SP'},
      {name: 'Pratânia', code: 'SP'},
      {name: 'Presidente Alves', code: 'SP'},
      {name: 'Presidente Bernardes', code: 'SP'},
      {name: 'Presidente Epitácio', code: 'SP'},
      {name: 'Presidente Prudente', code: 'SP'},
      {name: 'Presidente Venceslau', code: 'SP'},
      {name: 'Promissão', code: 'SP'},
      {name: 'Quadra', code: 'SP'},
      {name: 'Quatá', code: 'SP'},
      {name: 'Queiroz', code: 'SP'},
      {name: 'Queluz', code: 'SP'},
      {name: 'Quintana', code: 'SP'},
      {name: 'Rafard', code: 'SP'},
      {name: 'Rancharia', code: 'SP'},
      {name: 'Redenção da Serra', code: 'SP'},
      {name: 'Regente Feijó', code: 'SP'},
      {name: 'Reginópolis', code: 'SP'},
      {name: 'Registro', code: 'SP'},
      {name: 'Restinga', code: 'SP'},
      {name: 'Ribeira', code: 'SP'},
      {name: 'Ribeirão Bonito', code: 'SP'},
      {name: 'Ribeirão Branco', code: 'SP'},
      {name: 'Ribeirão Corrente', code: 'SP'},
      {name: 'Ribeirão do Sul', code: 'SP'},
      {name: 'Ribeirão dos Índios', code: 'SP'},
      {name: 'Ribeirão Grande', code: 'SP'},
      {name: 'Ribeirão Pires', code: 'SP'},
      {name: 'Ribeirão Preto', code: 'SP'},
      {name: 'Rifaina', code: 'SP'},
      {name: 'Rincão', code: 'SP'},
      {name: 'Rinópolis', code: 'SP'},
      {name: 'Rio Claro', code: 'SP'},
      {name: 'Rio das Pedras', code: 'SP'},
      {name: 'Rio Grande da Serra', code: 'SP'},
      {name: 'Riolândia', code: 'SP'},
      {name: 'Riversul', code: 'SP'},
      {name: 'Rosana', code: 'SP'},
      {name: 'Roseira', code: 'SP'},
      {name: 'Rubiácea', code: 'SP'},
      {name: 'Rubinéia', code: 'SP'},
      {name: 'Sabino', code: 'SP'},
      {name: 'Sagres', code: 'SP'},
      {name: 'Sales', code: 'SP'},
      {name: 'Sales Oliveira', code: 'SP'},
      {name: 'Salesópolis', code: 'SP'},
      {name: 'Salmourão', code: 'SP'},
      {name: 'Saltinho', code: 'SP'},
      {name: 'Salto', code: 'SP'},
      {name: 'Salto de Pirapora', code: 'SP'},
      {name: 'Salto Grande', code: 'SP'},
      {name: 'Sandovalina', code: 'SP'},
      {name: 'Santa Adélia', code: 'SP'},
      {name: 'Santa Albertina', code: 'SP'},
      {name: 'Santa Bárbara do Oeste', code: 'SP'},
      {name: 'Santa Branca', code: 'SP'},
      {name: 'Santa Clara do Oeste', code: 'SP'},
      {name: 'Santa Cruz da Conceição', code: 'SP'},
      {name: 'Santa Cruz da Esperança', code: 'SP'},
      {name: 'Santa Cruz das Palmeiras', code: 'SP'},
      {name: 'Santa Cruz do Rio Pardo', code: 'SP'},
      {name: 'Santa Ernestina', code: 'SP'},
      {name: 'Santa Fé do Sul', code: 'SP'},
      {name: 'Santa Gertrudes', code: 'SP'},
      {name: 'Santa Isabel', code: 'SP'},
      {name: 'Santa Lúcia', code: 'SP'},
      {name: 'Santa Maria da Serra', code: 'SP'},
      {name: 'Santa Mercedes', code: 'SP'},
      {name: 'Santa Rita do Oeste', code: 'SP'},
      {name: 'Santa Rita do Passa Quatro', code: 'SP'},
      {name: 'Santa Rosa de Viterbo', code: 'SP'},
      {name: 'Santa Salete', code: 'SP'},
      {name: 'Santana da Ponte Pensa', code: 'SP'},
      {name: 'Santana de Parnaíba', code: 'SP'},
      {name: 'Santo Anastácio', code: 'SP'},
      {name: 'Santo André', code: 'SP'},
      {name: 'Santo Antônio da Alegria', code: 'SP'},
      {name: 'Santo Antônio de Posse', code: 'SP'},
      {name: 'Santo Antônio do Aracanguá', code: 'SP'},
      {name: 'Santo Antônio do Jardim', code: 'SP'},
      {name: 'Santo Antônio do Pinhal', code: 'SP'},
      {name: 'Santo Expedito', code: 'SP'},
      {name: 'Santópolis do Aguapeí', code: 'SP'},
      {name: 'Santos', code: 'SP'},
      {name: 'São Bento do Sapucaí', code: 'SP'},
      {name: 'São Bernardo do Campo', code: 'SP'},
      {name: 'São Caetano do Sul', code: 'SP'},
      {name: 'São Carlos', code: 'SP'},
      {name: 'São Francisco', code: 'SP'},
      {name: 'São João da Boa Vista', code: 'SP'},
      {name: 'São João das Duas Pontes', code: 'SP'},
      {name: 'São João de Iracema', code: 'SP'},
      {name: 'São João do Pau do Alho', code: 'SP'},
      {name: 'São Joaquim da Barra', code: 'SP'},
      {name: 'São José da Bela Vista', code: 'SP'},
      {name: 'São José do Barreiro', code: 'SP'},
      {name: 'São José do Rio Pardo', code: 'SP'},
      {name: 'São José do Rio Preto', code: 'SP'},
      {name: 'São José dos Campos', code: 'SP'},
      {name: 'São Lourenço da Serra', code: 'SP'},
      {name: 'São Luís do Paraitinga', code: 'SP'},
      {name: 'São Manuel', code: 'SP'},
      {name: 'São Miguel Arcanjo', code: 'SP'},
      {name: 'São Paulo', code: 'SP'},
      {name: 'São Pedro', code: 'SP'},
      {name: 'São Pedro do Turvo', code: 'SP'},
      {name: 'São Roque', code: 'SP'},
      {name: 'São Sebastião', code: 'SP'},
      {name: 'São Sebastião da Grama', code: 'SP'},
      {name: 'São Simão', code: 'SP'},
      {name: 'São Vicente', code: 'SP'},
      {name: 'Sarapuí', code: 'SP'},
      {name: 'Sarutaiá', code: 'SP'},
      {name: 'Sebastianópolis do Sul', code: 'SP'},
      {name: 'Serra Azul', code: 'SP'},
      {name: 'Serra Negra', code: 'SP'},
      {name: 'Serrana', code: 'SP'},
      {name: 'Sertãozinho', code: 'SP'},
      {name: 'Sete Barras', code: 'SP'},
      {name: 'Severínia', code: 'SP'},
      {name: 'Silveiras', code: 'SP'},
      {name: 'Socorro', code: 'SP'},
      {name: 'Sorocaba', code: 'SP'},
      {name: 'Sud Mennucci', code: 'SP'},
      {name: 'Sumaré', code: 'SP'},
      {name: 'Suzanápolis', code: 'SP'},
      {name: 'Suzano', code: 'SP'},
      {name: 'Tabapuã', code: 'SP'},
      {name: 'Tabatinga', code: 'SP'},
      {name: 'Taboão da Serra', code: 'SP'},
      {name: 'Taciba', code: 'SP'},
      {name: 'Taguaí', code: 'SP'},
      {name: 'Taiaçu', code: 'SP'},
      {name: 'Taiúva', code: 'SP'},
      {name: 'Tambaú', code: 'SP'},
      {name: 'Tanabi', code: 'SP'},
      {name: 'Tapiraí', code: 'SP'},
      {name: 'Tapiratiba', code: 'SP'},
      {name: 'Taquaral', code: 'SP'},
      {name: 'Taquaritinga', code: 'SP'},
      {name: 'Taquarituba', code: 'SP'},
      {name: 'Taquarivaí', code: 'SP'},
      {name: 'Tarabai', code: 'SP'},
      {name: 'Tarumã', code: 'SP'},
      {name: 'Tatuí', code: 'SP'},
      {name: 'Taubaté', code: 'SP'},
      {name: 'Tejupá', code: 'SP'},
      {name: 'Teodoro Sampaio', code: 'SP'},
      {name: 'Terra Roxa', code: 'SP'},
      {name: 'Tietê', code: 'SP'},
      {name: 'Timburi', code: 'SP'},
      {name: 'Torre de Pedra', code: 'SP'},
      {name: 'Torrinha', code: 'SP'},
      {name: 'Trabiju', code: 'SP'},
      {name: 'Tremembé', code: 'SP'},
      {name: 'Três Fronteiras', code: 'SP'},
      {name: 'Tuiuti', code: 'SP'},
      {name: 'Tupã', code: 'SP'},
      {name: 'Tupi Paulista', code: 'SP'},
      {name: 'Turiúba', code: 'SP'},
      {name: 'Turmalina', code: 'SP'},
      {name: 'Ubarana', code: 'SP'},
      {name: 'Ubatuba', code: 'SP'},
      {name: 'Ubirajara', code: 'SP'},
      {name: 'Uchoa', code: 'SP'},
      {name: 'União Paulista', code: 'SP'},
      {name: 'Urânia', code: 'SP'},
      {name: 'Uru', code: 'SP'},
      {name: 'Urupês', code: 'SP'},
      {name: 'Valentim Gentil', code: 'SP'},
      {name: 'Valinhos', code: 'SP'},
      {name: 'Valparaíso', code: 'SP'},
      {name: 'Vargem', code: 'SP'},
      {name: 'Vargem Grande do Sul', code: 'SP'},
      {name: 'Vargem Grande Paulista', code: 'SP'},
      {name: 'Várzea Paulista', code: 'SP'},
      {name: 'Vera Cruz', code: 'SP'},
      {name: 'Vinhedo', code: 'SP'},
      {name: 'Viradouro', code: 'SP'},
      {name: 'Vista Alegre do Alto', code: 'SP'},
      {name: 'Vitória Brasil', code: 'SP'},
      {name: 'Votorantim', code: 'SP'},
      {name: 'Votuporanga', code: 'SP'},
      {name: 'Zacarias', code: 'SP'},
    ];

    this.listaRegiao= [
      {"code": 1,"name": "Região Metropolitana de São Paulo"},
      {"code": 2,"name": "Região Metropolitana de Campinas"},
      {"code": 3,"name": "Região Metropolitana de Ribeirão Preto"},
      {"code": 4,"name": "Região Metropolitana de São José do Rio Preto"}, 
      {"code": 5,"name": "Região Metropolitana de Sorocaba"}, 
      {"code": 6,"name": "Região Metropolitana de Baixada Santista"}, 
      {"code": 7,"name": "Região Metropolitana de Vale do Paraíba e Litoral Norte"}, 
      {"code": 8,"name": "Região Metropolitana de Araçatuba"}, 
      {"code": 9,"name": "Região Metropolitana de Araraquara"}, 
      {"code": 10, "name": "Região Metropolitana de Assis"}, 
      {"code": 11,"name": "Região Metropolitana de Bauru"}, 
      {"code": 12,"name": "Região Metropolitana de Marília"}, 
      {"code": 13,"name": "Região Metropolitana de Prescodeente Prudente"}, 
      {"code": 14,"name": "Região Metropolitana de Registro"}, 
      {"code": 15,"name": "Região Metropolitana de São José dos Campos"}, 
      {"code": 16,"name": "Região Metropolitana de Piracicaba"}, 
      {"code": 17,"name": "Região Metropolitana de Franca"}, 
      {"code": 18,"name": "Região Metropolitana de Itapetininga"},
      {"code": 19,"name": "Região Metropolitana de Itapeva"}
    ]

  }

  cadastrar(){
    if(!this.validarDados()){
      this.messageService.add({severity:'error', summary: 'Erro', detail: 'Verifique os dados informados.', life: 3000});
      return false
    }
    this.gravarDados(this.register);
    return true
  }

  validarDados(){
    if(!this.register.nome || !this.register.nomeFantasia || !this.register.cnpj || !this.register.logradouro  || 
      !this.register.numero || !this.register.bairro || !this.register.complemento || !this.register.cidade || 
      !this.register.uf || !this.register.cep || !this.register.usuario || !this.register.senha){
      return false
    }
    return true;
  }

  gravarDados(register:Register){

    this.registerDados.nome = register.nome;
    this.registerDados.nomeFantasia = register.nomeFantasia;
    this.registerDados.cnpj = register.cnpj;
    this.registerDados.endereco.push({
      'logradouro': register.logradouro,
      'numero': register.numero,
      'bairro': register.bairro,
      'complemento': register.complemento,
      'cidade': register.logradouro,
      'uf': register.uf,
      'cep': register.cep,
    })
      this.registerService.gravarDadosCadastro(this.registerDados).subscribe(data => {
      console.log(data);
    })
  }

  voltar(){
    this.operacao = Operacao.SIGIN;
  }

  limparMensagem(){
    this.messageService.clear();
  }

  adicionarValorUf(cidade:any){
    if(cidade){
      this.register.uf = 'SP';
    } else {
      this.register.uf = '';
    }
  }

}
